SeniorProject_v01/SeniorProject_v01/urls.py
from datetime import datetime
from django.conf.urls import include, url
import django.contrib.auth.views
from django.contrib.auth import views as auth_views

import app.views as core_views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', app.views.home, name='home'),
    url(r'^home$', app.views.home, name='home'),
    url(r'^events', app.views.events, name='events'),
    url(r'^search$', app.views.search, name='search'),
    url(r'^event/(?P<event_id>[0-9]+)/$', app.views.eventdetail, name='eventdetail'),
    url(r'^upcoming$', app.views.upcoming, name='upcoming'),    
    url(r'^event/edit/(?P<pk>\d+)/$', app.views.EditEvent.as_view(), name='editevent'),
    url(r'^create$', app.views.create, name='create'),
    url(r'^error$', app.views.error, name='error'),
   
   # USER REGISTRATION URLS ##################################################
    url(r'^signup/$', app.views.signup,  name='signup'),
    url(r'^confirm_email/$', app.views.signup,  name='user_confirmation'),
    url(r'^successful_confirmation/$', app.views.signup,  name='successful_confirmation'),
    url(r'^invalid_activation_link/$', app.views.signup,  name='invalid_activation'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        app.views.activate, name='activate'),

    # USER PASSWORD RESET URLS ##################################################
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    # TESTING URLS ###########################################################
  
    url(r'^eventlist$', app.views.eventlist, name='eventlist'),
    url(r'^test', app.views.test, name='test'),



    # USER MANAGEMENT URLS ###################################################

    
     url(r'^login/$',
        django.contrib.auth.views.login,  
        {
            'template_name': 'app/login.html', 
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),

    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    url(r'^admin/', include(admin.site.urls)),
]

SeniorProject_v01/app/models.py
"""
Definition of models.
"""

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from datetime import datetime
import googlemaps

# Create your models here.

class PermissionLevel(models.Model):
    level = models.IntegerField()
    level_name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.level) + ' - ' + self.level_name


class State(models.Model):
    state_name = models.CharField(max_length = 100, default = '')
    abbreviation = models.CharField(max_length = 2, default = '')

    def __str__(self):
        return self.state_name;


class Region(models.Model):
    region_name = models.CharField(max_length=255, default = '')
    abbreviation = models.CharField(max_length=6, default = '')

    def __str__(self):
        return self.region_name
    

class District(models.Model):
    district_name = models.CharField(max_length=255, default = '')
    pointman_ID = models.ForeignKey(User)
    region_ID = models.ForeignKey(Region)

    def __str__(self):
        return self.district_name


class Troop(models.Model):
    troop_number = models.IntegerField(default = 0)
    state = models.ForeignKey(State)
    district = models.ForeignKey(District)
    admin_ID = models.ManyToManyField(User)

    def __str__(self):
        return str(self.troop_number)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length = 500, default = '', null=True, blank=True)
    troop_number = models.ForeignKey(Troop, default=0, null=True, blank=True)
    permissions = models.ForeignKey(PermissionLevel, default=0)
    
    def __str__(self):
        return str(self.user.username)
    
    def get_troop(self):
        try:
            t = Troop.objects.get(troop_number=self.troop_number.troop_number)
            return t.troop_number
        except:
            return Troop.objects.get(troop_number=0) #'profile.gettroop error'

    def get_district(self):
        try:
            t = Troop.objects.get(troop_number=self.troop_number.troop_number)
            d = District.objects.get(district_name=t.district)
            return d
        except:
            return 'profile.getdistrict error'

    def get_district_pk(self):
        try:
            t = Troop.objects.get(troop_number=self.troop_number.troop_number)
            d = District.objects.get(district_name=t.district)
            return int(d.pk)
        except:
            return 'profile.getdistrictpk error'

    def get_permissions(self):
        try:
            p = PermissionLevel.objects.get(level=self.permissions.level)
            return p.level
        except:
            return 0

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()
    
    
class EventType(models.Model):
    name = models.CharField(max_length = 255, default = '')
    description = models.TextField(default = '')
    icon = models.FileField(null=True, blank=True)
    
    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length = 255)
    description = models.TextField(help_text='Enter a description of the event.')
    event_type = models.ForeignKey(EventType)
    date_start = models.DateTimeField(default = datetime.now)
    date_end = models.DateTimeField(default = datetime.now)
    address = models.CharField(max_length = 500, default = '', help_text='Enter the address of the event')
    coord_x = models.CharField(max_length = 255, default = '', null=True, blank=True)
    coord_y = models.CharField(max_length = 255, default = '', null=True, blank=True)
    google_location = models.CharField(max_length = 300, default = '', null=True, blank=True)
    district = models.ForeignKey(District, default = '0', null=True, blank=True)
    payment_url = models.URLField(default = 'https://www.', null=True, blank=True)
    primary_contact_name = models.CharField(max_length=255, default='')
    primary_contact_info = models.CharField(max_length=255, default='', help_text='(123) 333-4445')
    primary_contact_info_type = models.IntegerField(null=True, blank=True)
    creation_date = models.DateTimeField(default = datetime.now)
    creation_user = models.ForeignKey(User, null=True, blank=True)

    def __str__(self):
        return self.name;

    def get_absolute_url(self):
        url = '/event/' + str(self.id)
        return u'<a href="%s">%s</a>' % (url, str(self.name))

    def get_troop(self):
        #u = self.creation_user
        #t = Troop.objects.get(troop_number=u.profile.get_troop())
        #return t.troop_number

        try:
            t = Troop.objects.get(troop_number=self.creation_user.profile.troop_number.troop_number)
            return t.troop_number
        except:
            return Troop.objects.get(troop_number=0) #'event.gettroop error'


class SearchEvent(models.Model):
    name = models.CharField(max_length = 255, blank=True, null=True)
    description = models.CharField(max_length=255, default = '', blank=True, null=True)
    event_type = models.ForeignKey(EventType, blank=True, null=True)
    date_start = models.DateField(default = '', blank=True, null=True)
    district = models.ForeignKey(District, blank=True, null=True)
    primary_contact_ID = models.ForeignKey(User, blank=True, null=True)


class ListEvent(models.Model):
    event_type = models.ForeignKey(EventType, blank=True, null=True)
    date_start = models.DateField(default = '', blank=True, null=True)
    district = models.ForeignKey(District, blank=True, null=True)


class autofill(models.Model):
    address = models.CharField(max_length=400)

SeniorProject_v01/app/templates/app/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

SeniorProject_v01/app/templates/app/authentication_error.html
<div class="navbar-offset"></div>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Error!</strong> You are not authenticated. Please <a href="login" class="alert-link">login</a> to continue.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

SeniorProject_v01/app/templates/app/create.html
{% extends "app/layout.html" %}

{% load staticfiles %}
{% load widget_tweaks %}
{% load append_ast_if_req %}

{% block head %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
    {{ form.media }}

<style>
.bootstrap-datetimepicker-widget table td, .bootstrap-datetimepicker-widget table th {
    text-align: center;
    border-radius: 0;
    background-color: white;
}
</style>
{% endblock %}

{% block content %}

    <h1 class="text-uppercase">Create a New Event</h1>
    <div class="row justify-content-center">
        <div class="col-8">
            <form method="POST">
            {% csrf_token %}
    
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                <div class="form-group">
                    <label for=" {{ form.name.id_for_label }}">{{ form.name | append_ast_if_req }}:</label>
                    {{ form.name|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for=" {{ form.description.id_for_label }}">{{ form.description | append_ast_if_req }}:</label>
                    {{ form.description|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for=" {{ form.address.id_for_label }}">{{ form.address | append_ast_if_req }}:</label>
                    {{ form.address|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <!-- if user is district or site admin, let them select a district -->
                {% if permissions >= 0 %}
                <div class="form-group">
                    <label for=" {{ form.district.id_for_label }}">{{ form.district | append_ast_if_req }}:</label>
                    {{ form.district|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>
                {% endif %}

                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for=" {{ form.date_start.id_for_label }}">{{ form.date_start | append_ast_if_req }}:</label>
                            <div class="input-group mb-3">
                                {{ form.date_start|add_class:'form-control' }}
                                <span class="help-block">{{ error }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <div class="form-group">
                            <label for=" {{ form.date_end.id_for_label }}">{{ form.date_end | append_ast_if_req }}:</label>
                            <div class="input-group mb-3">
                                {{ form.date_end|add_class:'form-control' }}
                                <span class="help-block">{{ error }}</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for=" {{ form.event_type.id_for_label }}">{{ form.event_type | append_ast_if_req }}:</label>
                    {{ form.event_type|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for=" {{ form.payment_url.id_for_label }}">{{ form.payment_url | append_ast_if_req }}:</label>
                    {{ form.payment_url|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for="{{ form.primary_contact_name.id_for_label }}">{{ form.primary_contact_name | append_ast_if_req }}:</label>
                    {{ form.primary_contact_name|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label>Contact Type:</label>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="primary_contact_info_type1" id="primary_contact_info_type1" value="1">
                        <i class="fas fa-envelope"></i>
                        <label class="form-check-label" for="primary_contact_info_type1">Email</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="primary_contact_info_type2" id="primary_contact_info_type2" value="2">
                        <i class="fas fa-phone"></i>
                        <label class="form-check-label" for="primary_contact_info_type1">Phone</label>
                    </div>
                </div>

                <div class="form-group">
                    <label for=" {{ form.primary_contact_info.id_for_label }}">Contact Information:</label>
                    <input type="text" name="primary_contact_info" maxlength="255" class="form-control" required="" id="id_primary_contact_info" placeholder="(123) 333-4445 or me@email.com">
                    <span class="help-block">{{ error }}</span>
                </div>

                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>


    <div class="col">
    </div>

{% endblock %}


{% block scripts %}
<!-- autocomplete on type in search box -->
<script>
    function init() {
        var input = document.getElementById('locationTextField');
        var autocomplete = new google.maps.places.Autocomplete(input);
    }

    google.maps.event.addDomListener(window, 'load', init);
</script>

{% endblock %}

SeniorProject_v01/app/templates/app/error.html
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block content %}

<div class="navbar-offset"></div>

<div class="row">
    <div class="col">
        <div class="align-items-center">
            <img src="{% static 'app/img/error2.png' %}" class="float-left" style="height:12rem;"/>
            <h1 class="display-2 text-danger align-items-center"><i class="fas fa-exclamation-triangle fa-sm text-danger"></i> {{ error_code }} Error</h1>
        </div>
    </div>
</div>

<div class="jumbotron">
    <h1 class="text-center">Sorry about that!</h1>
    <p class="text-center h4">{{ error_msg }}</p>
    <p>&nbsp;</p>
</div>

{% endblock %}

SeniorProject_v01/app/templates/app/event_update.html
{% extends "app/layout.html" %}

{% load staticfiles %}
{% load widget_tweaks %}
{% load append_ast_if_req %}

{% block head %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
    {{ form.media }}

<style>
.bootstrap-datetimepicker-widget table td, .bootstrap-datetimepicker-widget table th {
    text-align: center;
    border-radius: 0;
    background-color: white;
}
</style>
{% endblock %}

{% block content %}

{% if permissions < 2 %}

<h1>You do not have permission to view this page</h1>

{% endif %}


    <h1 class="text-uppercase">Modify Event</h1>
    <div class="row justify-content-center">
        <div class="col-8">
            <form method="POST">
            {% csrf_token %}
    
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                <div class="form-group">
                    <label for=" {{ form.name.id_for_label }}">{{ form.name | append_ast_if_req }}:</label>
                    {{ form.name|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for=" {{ form.description.id_for_label }}">{{ form.description | append_ast_if_req }}:</label>
                    {{ form.description|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for=" {{ form.address.id_for_label }}">{{ form.address | append_ast_if_req }}:</label>
                    {{ form.address|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <!-- if user is district or site admin, let them select a district -->
                {% if permissions >= 0 %}
                <div class="form-group">
                    <label for=" {{ form.district.id_for_label }}">{{ form.district | append_ast_if_req }}:</label>
                    {{ form.district|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>
                {% endif %}

                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for=" {{ form.date_start.id_for_label }}">{{ form.date_start | append_ast_if_req }}:</label>
                            <div class="input-group mb-3">
                                {{ form.date_start|add_class:'form-control' }}
                                <span class="help-block">{{ error }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <div class="form-group">
                            <label for=" {{ form.date_end.id_for_label }}">{{ form.date_end | append_ast_if_req }}:</label>
                            <div class="input-group mb-3">
                                {{ form.date_end|add_class:'form-control' }}
                                <span class="help-block">{{ error }}</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for=" {{ form.event_type.id_for_label }}">{{ form.event_type | append_ast_if_req }}:</label>
                    {{ form.event_type|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for=" {{ form.payment_url.id_for_label }}">{{ form.payment_url | append_ast_if_req }}:</label>
                    {{ form.payment_url|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label for="{{ form.primary_contact_name.id_for_label }}">{{ form.primary_contact_name | append_ast_if_req }}:</label>
                    {{ form.primary_contact_name|add_class:'form-control' }}
                    <span class="help-block">{{ error }}</span>
                </div>

                <div class="form-group">
                    <label>Contact Type:</label>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="primary_contact_info_type1" id="primary_contact_info_type1" value="1">
                        <i class="fas fa-envelope"></i>
                        <label class="form-check-label" for="primary_contact_info_type1">Email</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="primary_contact_info_type2" id="primary_contact_info_type2" value="2">
                        <i class="fas fa-phone"></i>
                        <label class="form-check-label" for="primary_contact_info_type1">Phone</label>
                    </div>
                </div>

                <div class="form-group">
                    <label for=" {{ form.primary_contact_info.id_for_label }}">Contact Information:</label>
                    <input type="text" name="primary_contact_info" maxlength="255" class="form-control" required="" id="id_primary_contact_info" placeholder="(123) 333-4445 or me@email.com">
                    <span class="help-block">{{ error }}</span>
                </div>

                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>


    <div class="col">
    </div>

{% endblock %}


{% block scripts %}
<!-- autocomplete on type in search box -->
<script>
    function init() {
        var input = document.getElementById('locationTextField');
        var autocomplete = new google.maps.places.Autocomplete(input);
    }

    google.maps.event.addDomListener(window, 'load', init);
</script>

{% endblock %}

SeniorProject_v01/app/templates/app/eventdetail.html
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block content %}

    <div class="row row-stripped color-bg">

        <div class="col-2 text-right">
		    <div class="time">
                {% if event.date_start.day == event.date_end.day %}
				    <div class="bk-day">{{ event.date_start.day}}</div>
                {% else %}
                    <div class="bk-day-multiple">{{ event.date_start.day}} - {{ event.date_end.day}}</div>
                {% endif %}
			    <div class="bk-month">{{ event.date_start|date:"M" }}</div>
		    </div>
	    </div>

		<div class="col-md-10">
			<div class="text-uppercase">
                <strong>{{ event.name }}</strong>
                <!-- if user is district admin or higher, give edit option -->
                {% if permissions > 2 %}
                <a class="btn btn-primary" href="{% url 'editevent' pk=event.id %}" role="button"><i class="fas fa-edit"></i> Edit</a>
                {% elif event_troop == user_troop %}
                <a class="btn btn-primary" href="{% url 'editevent' pk=event.id %}" role="button"><i class="fas fa-edit"></i> Edit</a>
                {% endif %}
            </div>
			<ul class="list-inline">
                {% if event.date_start.day == event.date_end.day %}
				    <li class="list-inline-item"><i class="fas fa-calendar-alt" aria-hidden="true"></i> {{ event.date_start|date:'l F jS, Y' }}</li>
				{% else %}
				    <li class="list-inline-item"><i class="fas fa-calendar-alt" aria-hidden="true"></i> {{ event.date_start|date:'M jS' }} - {{ event.date_end|date:'M jS, Y' }}</li>
                {% endif %}
                <li class="list-inline-item"><i class="fas fa-clock" aria-hidden="true"></i> {{ event.date_start|date:'g:i A' }} - {{ event.date_end|date:'g:i A' }}</li>
			</ul>
            <ul class="list-inline">
                <li class="list-inline-item"><i class="fas fa-location-arrow" aria-hidden="true"></i><strong> District: </strong> {{ event.district }}</li>
                <li class="list-inline-item">
                    {% if event.event_type.id == 6 %}
                        <img src="{% static 'app/img/icons/national.svg' %}" class="event-fas" />
                    {% elif event.event_type.id == 5 %}
                        <img src="{% static 'app/img/icons/regional.svg' %}" class="event-fas" />
                    {% elif event.event_type.id == 4 %}
                        <img src="{% static 'app/img/icons/community.svg' %}" class="event-fas" />
                    {% elif event.event_type.id == 3 %}
                        <img src="{% static 'app/img/icons/training.svg' %}" class="event-fas" />
                    {% elif event.event_type.id == 2 %}
                        <img src="{% static 'app/img/icons/backpack.svg' %}" class="event-fas" />
                    {% elif event.event_type.id == 1 %}
                        <img src="{% static 'app/img/icons/camping.svg' %}" class="event-fas" />
                    {% else %}
                        <i class="far fa-question-circle"></i>
                    {% endif %}

                    <strong>Category: </strong>{{ event.event_type}}
                </li>
			</ul>

            <table class="table">
                <tr>
                    <th scope="row">Description: </th>
                    <td>
                        {{ event.description }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Primary Contact: 
                    <td>
                        {{ event.primary_contact_name}}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Contact Information: </th>
                    <td>
                        {% if event.primary_contact_info_type == 1 %}
                            <i class="fas fa-envelope"></i> 
                        {% elif event.primary_contact_info_type == 0 %}
                            <i class="fas fa-phone"></i> 
                        {% endif %}
                        {{ event.primary_contact_info }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Payment: </th>
                    <td>
                        <a href="{{ event.payment_url }}">{{ event.payment_url }}</a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Address: </th>
                    <td>
                        {{ event.address }}
                        <br /><i class="far fa-compass"></i> <a href="{{ url }}" target="_blank"><strong>Get Directions</strong></a>
                    </td>

            </table>
		</div>

        <div id="map"></div>

<script>
    function initMap() {
        var location = {
            lat: {{ event.coord_x }},
            lng: {{ event.coord_y }}
            };

      var map = new google.maps.Map(
          document.getElementById('map'), {zoom: 14, center: location});

      var marker = new google.maps.Marker( {position: location, map: map} );
    }
</script>

</div>
{% endblock %}

{% block scripts %}
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA0aaavBcFWIBvn3Tnu86BYOpKHqYVqKR8&callback=initMap">
</script>


{% endblock %}

SeniorProject_v01/app/templates/app/eventlist.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}

<div class="wrapper-trans">

    {% if eventlist %}
    <ul>
    {% for event in eventlist %}
        <li>{{ event.name }} - <a class="btn btn-primary" href="/event/{{event.id}}" role="button">Link</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No events are available.</p>
    {% endif %}
</div>

{% endblock %}

{% block scripts %}

{% endblock %}

SeniorProject_v01/app/templates/app/invalid_activation.html
{% extends "app/layout.html" %}
{% load staticfiles %}

{% block content %}
 
<div class="alert alert-danger" role="alert">
  <h2 class="alert-heading"><strong>Activation Failed!</strong></h2>
  <p>This might be because:</p>
   <p>The account link has expired or incorrect,</p>
  <p class="mb-0"><a href="/password_reset" class="alert-link" style="text-decoration:underline; ">Click Here</a> to request a new activation email.</p>
</div>

{% endblock %}

SeniorProject_v01/app/templates/app/layout_index.html
{% load staticfiles %}
{% load in_group %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{{ title }} - OAF</title>   
    <!-- Bootstrap CSS and JS -->
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.4.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/headerlogin.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Open+Sans+Condensed:300" rel="stylesheet">

    {% block head %}
    {% endblock %}

</head>

<body id="index">

    <!-- insert navbar -->
    {% include 'app/navbar.html' %}

    <div class="container">

        <!-- MAIN CONTENT BLOCK HERE -->
        {% block content %}
        {% endblock %}

    </div>

    <!-- insert footer -->
    {% include 'app/footer.html' %}

    <!-- <script src="{% static 'app/scripts/jquery-3.3.1.min.js' %}"></script>-->
    
    <script src="{% static 'app/scripts/bootstrap.bundle.4.min.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-ui.1.12.1.min.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    <script src="{% static 'app/scripts/site.js' %}"></script>

    {% block scripts %}

    {% endblock %}

</body>
</html>

SeniorProject_v01/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}